releaseConfluenceDocument:
  gotemplatePath: "../doc_go_template.txt"
  confluenceSpec:
    url: "https://confluence.alauda.cn"
    parts:
    - username: stwu@alauda.io
      token: "NzI4NTU5OTQwODMzOlORfNckQcnu1SDEq0xCyGfu/JbJ"
    - username: huiyang1@alauda.io
      token: "NDE5NTI0ODAxMTMzOvFj/Fn/lSiKARc7aUslzB+ZfH5W"