releaseConfluenceDocument:
  documentImgDirectory: "/opt/s1mple/imgs"
  gotemplatePath: "/opt/s1mple/doc_go_template.txt"
  confluenceSpec:
    timeout: 5
    retryCount: 2
    url: "https://confluence.alauda.cn"
    parts:
    - username: stwu@alauda.io
      token: "NzI4NTU5OTQwODMzOlORfNckQcnu1SDEq0xCyGfu/JbJ"
    - username: huiyang1@alauda.io
      token: "NDE5NTI0ODAxMTMzOvFj/Fn/lSiKARc7aUslzB+ZfH5W"